# Generated by Django 4.2.7 on 2025-05-04 16:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название книги')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название книги')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('author_ru', models.CharField(max_length=255, null=True, verbose_name='Автор')),
                ('author_ky', models.CharField(max_length=255, null=True, verbose_name='Автор')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Изображение книги')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/files/', verbose_name='Файл книги')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('read_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Партнёр и Поддержка',
                'verbose_name_plural': 'Партнёры и Поддержки',
            },
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners_images/', verbose_name='Изображение')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_images', to='el_library.partner')),
            ],
            options={
                'verbose_name': 'Изображение партнёра и',
                'verbose_name_plural': 'Изображения партнёров и',
            },
        ),
    ]
