# Generated by Django 4.2.7 on 2025-05-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerimage',
            name='partner',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PartnerImage',
        ),
    ]
