# Generated by Django 4.2.7 on 2025-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprojects',
            name='title_2',
            field=models.CharField(default=1, max_length=255, verbose_name='основыные проекты'),
            preserve_default=False,
        ),
    ]
