# Generated by Django 4.2.7 on 2025-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_ourprojects_title_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprojects',
            name='title_2_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='основыные проекты'),
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='title_2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='основыные проекты'),
        ),
    ]
