# Generated by Django 4.2.7 on 2025-04-04 10:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Рейтинг книг(ТОП-3)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Рейтинг книг(ТОП-3)')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Рейтинг книг(ТОП-3)')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('place_ru', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('place_ky', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Книга')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Книга')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Книга')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото книги')),
            ],
            options={
                'verbose_name': 'Рейтинг книги',
                'verbose_name_plural': 'Рейтинг книг',
            },
        ),
        migrations.CreateModel(
            name='Catalogs_ElectronicLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка на подробнее')),
            ],
            options={
                'verbose_name': 'Каталог/Электронная библиотека',
                'verbose_name_plural': 'Каталоги/Электронные библиотеки',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('library', models.CharField(max_length=255, verbose_name='Название библиотеки')),
                ('library_ru', models.CharField(max_length=255, null=True, verbose_name='Название библиотеки')),
                ('library_ky', models.CharField(max_length=255, null=True, verbose_name='Название библиотеки')),
                ('adress', models.CharField(max_length=255, verbose_name='Адресс')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главные',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинки партнёров')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='ReadingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Рейтинг читателей(ТОП-3)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Рейтинг читателей(ТОП-3)')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Рейтинг читателей(ТОП-3)')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('place_ru', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('place_ky', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Рейтинг читателя')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Рейтинг читателя')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Рейтинг читателя')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото читателя')),
            ],
            options={
                'verbose_name': 'Рейтинг читателя',
                'verbose_name_plural': 'Рейтинг читателей',
            },
        ),
        migrations.CreateModel(
            name='WeOfferViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('selections', models.CharField(max_length=255, verbose_name='Подборка для вас')),
                ('selections_ru', models.CharField(max_length=255, null=True, verbose_name='Подборка для вас')),
                ('selections_ky', models.CharField(max_length=255, null=True, verbose_name='Подборка для вас')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на поподробнее')),
            ],
            options={
                'verbose_name': 'Предлагаем к Просмотру',
                'verbose_name_plural': 'Предлогают к просмотру',
            },
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners_images/', verbose_name='Изображение')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_images', to='base.partners')),
            ],
            options={
                'verbose_name': 'Изображение партнёра',
                'verbose_name_plural': 'Изображения партнёров',
            },
        ),
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo_images/', verbose_name='Изображение')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_images', to='base.logo')),
            ],
            options={
                'verbose_name': 'Изображение логов',
                'verbose_name_plural': 'Изображения лого',
            },
        ),
    ]
