# Generated by Django 4.2.7 on 2025-04-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksRating',
        ),
        migrations.DeleteModel(
            name='ReadingRating',
        ),
    ]
