# Generated by Django 4.2.7 on 2025-04-18 12:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_booksrating_delete_readingrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Рейтинг книг(ТОП-3)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Рейтинг книг(ТОП-3)')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Рейтинг книг(ТОП-3)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание книга')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание книга')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание книга')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото книги')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото книги')),
                ('image_ky', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото книги')),
            ],
            options={
                'verbose_name': 'Рейтинг книги',
                'verbose_name_plural': 'Рейтинг книг',
            },
        ),
        migrations.CreateModel(
            name='ReadingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Рейтинг читателей(ТОП-3)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Рейтинг читателей(ТОП-3)')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Рейтинг читателей(ТОП-3)')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('place_ru', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('place_ky', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Рейтинг читателя')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Рейтинг читателя')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Рейтинг читателя')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото читателя')),
            ],
            options={
                'verbose_name': 'Рейтинг читателя',
                'verbose_name_plural': 'Рейтинг читателей',
            },
        ),
        migrations.RemoveField(
            model_name='logo',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='library',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='library_ky',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='library_ru',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='phone',
        ),
        migrations.AddField(
            model_name='logo',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Изображение первое'),
        ),
        migrations.AddField(
            model_name='logo',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Изображение второе'),
        ),
        migrations.AddField(
            model_name='logo',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Изображение третье'),
        ),
        migrations.AddField(
            model_name='logo',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Изображение чётвёртое'),
        ),
        migrations.AddField(
            model_name='logo',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Изображение пятое'),
        ),
        migrations.AlterField(
            model_name='catalogs_electroniclibrary',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на подробнее'),
        ),
        migrations.DeleteModel(
            name='LogoImage',
        ),
    ]
