# Generated by Django 4.2.7 on 2025-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_booksrating_readingrating_remove_logo_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(verbose_name='Хедер')),
                ('header_ru', models.TextField(null=True, verbose_name='Хедер')),
                ('header_ky', models.TextField(null=True, verbose_name='Хедер')),
                ('footer', models.TextField(verbose_name='Футер')),
                ('footer_ru', models.TextField(null=True, verbose_name='Футер')),
                ('footer_ky', models.TextField(null=True, verbose_name='Футер')),
            ],
            options={
                'verbose_name': 'Хедер и Футер',
                'verbose_name_plural': 'Хедеры и Футеры',
            },
        ),
    ]
