# Generated by Django 4.2.7 on 2025-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_headerfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='links',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка'),
        ),
    ]
