# Generated by Django 4.2.7 on 2025-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_partners_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='links',
        ),
        migrations.AddField(
            model_name='partnerimage',
            name='links',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
