# Generated by Django 4.2.7 on 2025-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_partners_links_partnerimage_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='address_ky',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='address_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Иконки'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='icons_ky',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Иконки'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='icons_ru',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Иконки'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='logo_ky',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='logo_ru',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Логотип'),
        ),
    ]
