# Generated by Django 4.2.7 on 2025-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_headerfooter_address_headerfooter_address_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrating',
            name='images_ky',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото читателя'),
        ),
        migrations.AddField(
            model_name='readingrating',
            name='images_ru',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото читателя'),
        ),
    ]
