# Generated by Django 4.2.7 on 2025-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_readingrating_images_ky_readingrating_images_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerfooter',
            name='icons_ky',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='icons_ru',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='logo_ky',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='logo_ru',
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='about_library',
            field=models.URLField(blank=True, null=True, verbose_name='Страница о библиотеке'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='afisha',
            field=models.URLField(blank=True, null=True, verbose_name='Афиша'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='catalog',
            field=models.URLField(blank=True, null=True, verbose_name='Каталог'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='el_library',
            field=models.URLField(blank=True, null=True, verbose_name='Электронная библиотека'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Библиотеки'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='name_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Библиотеки'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Библиотеки'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='news',
            field=models.URLField(blank=True, null=True, verbose_name='Новости'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='page_for_readers',
            field=models.URLField(blank=True, null=True, verbose_name='Читателям'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телефона'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='pro_activity',
            field=models.URLField(blank=True, null=True, verbose_name='Профессиональная деятельность'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='projects',
            field=models.URLField(blank=True, null=True, verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='services',
            field=models.URLField(blank=True, null=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='supports',
            field=models.URLField(blank=True, null=True, verbose_name='Поддержать библиотеку'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_about_library',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='O библиотеке'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_about_library_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='O библиотеке'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_about_library_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='O библиотеке'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_afisha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мероприятия и деятельность'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_afisha_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мероприятия и деятельность'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_afisha_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мероприятия и деятельность'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_for_readers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Читателям'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_for_readers_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Читателям'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='title_for_readers_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Читателям'),
        ),
    ]
