# Generated by Django 4.2.7 on 2025-05-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_headerfooter_icons_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='facebook_icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='google_icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='instagram_icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='youtube_icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
    ]
