# Generated by Django 4.2.7 on 2025-05-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_headerfooter_facebook_icon_headerfooter_google_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksrating',
            name='place',
            field=models.CharField(default=1, max_length=255, verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booksrating',
            name='place_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Место'),
        ),
    ]
