# Generated by Django 4.2.7 on 2025-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_booksrating_place_booksrating_place_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogs_electroniclibrary',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
