# Generated by Django 4.2.7 on 2025-05-05 12:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_catalogs_electroniclibrary_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на подробнее')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Электронная библиотека',
                'verbose_name_plural': 'Электронные библиотеки',
            },
        ),
        migrations.RenameModel(
            old_name='Catalogs_ElectronicLibrary',
            new_name='Catalogs',
        ),
        migrations.RemoveField(
            model_name='booksrating',
            name='place_ky',
        ),
        migrations.RemoveField(
            model_name='booksrating',
            name='place_ru',
        ),
    ]
