# Generated by Django 4.2.7 on 2025-05-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_electroniclibrary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogs',
            options={'verbose_name': 'Электронная библиотека', 'verbose_name_plural': 'Электронные библиотеки'},
        ),
    ]
