# Generated by Django 4.2.7 on 2025-05-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_catalogs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogs',
            options={'verbose_name': 'Каталоги', 'verbose_name_plural': 'Каталоги'},
        ),
    ]
