# Generated by Django 4.2.7 on 2025-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_catalogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='about_library_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Страница о библиотеке'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='about_library_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Страница о библиотеке'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='afisha_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Афиша'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='afisha_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Афиша'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='catalog_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Каталог'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='catalog_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Каталог'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='el_library_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Электронная библиотека'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='el_library_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Электронная библиотека'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='icons_ky',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Иконки'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='icons_ru',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Иконки'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='logo_ky',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='logo_ru',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='news_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Новости'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='news_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Новости'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='page_for_readers_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Читателям'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='page_for_readers_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Читателям'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='phone_number_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телефона'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='phone_number_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телефона'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='pro_activity_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Профессиональная деятельность'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='pro_activity_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Профессиональная деятельность'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='projects_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='projects_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='services_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='services_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='supports_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Поддержать библиотеку'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='supports_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Поддержать библиотеку'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='about_library',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Страница о библиотеке'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='afisha',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Афиша'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='catalog',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='el_library',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Электронная библиотека'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='news',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='page_for_readers',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Читателям'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='pro_activity',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Профессиональная деятельность'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='projects',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='services',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='supports',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Поддержать библиотеку'),
        ),
    ]
