# Generated by Django 4.2.7 on 2025-05-10 17:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_headerfooter_about_library_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksrating',
            name='description',
        ),
        migrations.RemoveField(
            model_name='booksrating',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='booksrating',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='booksrating',
            name='image_ky',
        ),
        migrations.RemoveField(
            model_name='booksrating',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='readingrating',
            name='images_ky',
        ),
        migrations.RemoveField(
            model_name='readingrating',
            name='images_ru',
        ),
        migrations.AddField(
            model_name='booksrating',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор книги'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='author_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор книги'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='author_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор книги'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='book',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='book_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='book_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='code',
            field=models.CharField(default='default_code', max_length=255, verbose_name='Код цивилизации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booksrating',
            name='code_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Код цивилизации'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='code_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Код цивилизации'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='place_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='booksrating',
            name='place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='readingrating',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Имя/Сколько прочитано'),
        ),
        migrations.AlterField(
            model_name='readingrating',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Имя/Сколько прочитано'),
        ),
        migrations.AlterField(
            model_name='readingrating',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Имя/Сколько прочитано'),
        ),
    ]
