# Generated by Django 4.2.7 on 2025-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_booksrating_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='facebook_icon_ky',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='facebook_icon_ru',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='google_icon_ky',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='google_icon_ru',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='instagram_icon_ky',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='instagram_icon_ru',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='youtube_icon_ky',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='youtube_icon_ru',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
    ]
