# Generated by Django 4.2.7 on 2025-05-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_headerfooter_facebook_icon_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerfooter',
            name='facebook_icon_ky',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='facebook_icon_ru',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='google_icon_ky',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='google_icon_ru',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='instagram_icon_ky',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='instagram_icon_ru',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='youtube_icon_ky',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='youtube_icon_ru',
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='facebook_icon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка Facebook'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='google_icon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка Google'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='instagram_icon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка Instagram'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='youtube_icon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка YouTube'),
        ),
    ]
