# Generated by Django 4.2.7 on 2025-05-13 12:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_headerfooter_facebook_icon_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_reg', models.CharField(max_length=255, verbose_name='Заголовок для регистрации')),
                ('title_reg_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок для регистрации')),
                ('title_reg_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок для регистрации')),
                ('description_reg', ckeditor.fields.RichTextField(verbose_name='Описание для регистрации')),
                ('description_reg_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание для регистрации')),
                ('description_reg_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание для регистрации')),
                ('image_reg', models.ImageField(upload_to='register-logo/', verbose_name='Изображение для регистрации')),
                ('title_log', models.CharField(max_length=255, verbose_name='Заголовок для выхода')),
                ('title_log_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок для выхода')),
                ('title_log_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок для выхода')),
                ('description_log', ckeditor.fields.RichTextField(verbose_name='Описание для выхода')),
                ('description_log_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание для выхода')),
                ('description_log_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание для выхода')),
            ],
            options={
                'verbose_name': 'Текст для Регистрации и Входа',
                'verbose_name_plural': 'Тексты для Регистрации и Входа',
            },
        ),
    ]
