# Generated by Django 4.2.7 on 2025-05-13 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_registerlogout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlogout',
            name='description_log',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание для выхода'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='description_log_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание для выхода'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='description_log_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание для выхода'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='description_reg',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание для регистрации'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='description_reg_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание для регистрации'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='description_reg_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание для регистрации'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='image_reg',
            field=models.ImageField(blank=True, null=True, upload_to='register-logo/', verbose_name='Изображение для регистрации'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='title_log',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для выхода'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='title_log_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для выхода'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='title_log_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для выхода'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='title_reg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для регистрации'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='title_reg_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для регистрации'),
        ),
        migrations.AlterField(
            model_name='registerlogout',
            name='title_reg_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для регистрации'),
        ),
    ]
