# Generated by Django 4.2.7 on 2025-05-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_registerlogout_description_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weofferviewing',
            name='video_file',
        ),
        migrations.AddField(
            model_name='weofferviewing',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
