# Generated by Django 4.2.7 on 2025-04-18 12:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afisha',
        ),
        migrations.RemoveField(
            model_name='events',
            name='details_link',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time_of_the_event',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time_of_the_event_ky',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time_of_the_event_ru',
        ),
        migrations.AddField(
            model_name='events',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Общая информация'),
        ),
        migrations.AddField(
            model_name='events',
            name='information_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Общая информация'),
        ),
        migrations.AddField(
            model_name='events',
            name='information_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Общая информация'),
        ),
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на "подробнее'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(help_text='Объявление о мероприятиях', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title_ky',
            field=models.CharField(help_text='Объявление о мероприятиях', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title_ru',
            field=models.CharField(help_text='Объявление о мероприятиях', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
