# Generated by Django 4.2.7 on 2025-04-11 09:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=155, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Категорий профессиональная деятельность',
                'verbose_name_plural': 'Категорий профессиональная деятельности',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, unique=True, verbose_name='заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='описание')),
                ('links', models.CharField(max_length=355, verbose_name='Ссылка')),
                ('description_details', ckeditor.fields.RichTextField(verbose_name='детальное описание')),
                ('description_details_ru', ckeditor.fields.RichTextField(null=True, verbose_name='детальное описание')),
                ('description_details_ky', ckeditor.fields.RichTextField(null=True, verbose_name='детальное описание')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_activity.typeactivity', verbose_name='category')),
                ('type_ky', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_activity.typeactivity', verbose_name='category')),
                ('type_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_activity.typeactivity', verbose_name='category')),
            ],
            options={
                'verbose_name': 'профессиональная деятельность',
                'verbose_name_plural': 'профессиональная деятельности',
            },
        ),
    ]
