# Generated by Django 4.2.7 on 2025-04-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('bookarrival_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.bookarrival')),
                ('special_feature', models.CharField(max_length=255, verbose_name='Особенность')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Каталог книги',
                'verbose_name_plural': 'Каталоги книг',
            },
            bases=('news.bookarrival',),
        ),
    ]
