# Generated by Django 4.2.7 on 2025-05-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='note_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='note_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='popular',
            field=models.BooleanField(blank=True, null=True, verbose_name='Популярное'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='read_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='special_feature_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Особенность'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='special_feature_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Особенность'),
        ),
    ]
