# Generated by Django 4.2.7 on 2025-05-05 11:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_catalog_note_ky_catalog_note_ru_catalog_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynews',
            name='date',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Дата и Время'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailynews',
            name='date_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Дата и Время'),
        ),
        migrations.AddField(
            model_name='dailynews',
            name='date_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Дата и Время'),
        ),
    ]
