# Generated by Django 4.2.7 on 2025-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_dailynews_date_dailynews_date_ky_dailynews_date_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookarrival',
            name='populars',
            field=models.BooleanField(blank=True, null=True, verbose_name='Популярное'),
        ),
    ]
