# Generated by Django 4.2.7 on 2025-04-25 10:15

import app.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Студент'), (2, 'Школьник'), (3, 'Пенсионер'), (4, 'Служащий'), (5, 'ОВЗ, ограниченные возможности здоровья'), (6, 'Другое')], default=6, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский')], default=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[app.users.models.User.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
