# Generated by Django 4.2.7 on 2025-05-15 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0002_remove_partnerimage_partner_delete_partner_and_more'),
        ('users', '0005_user_is_email_verified_user_reset_password_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='el_library.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прочитанная книга',
                'verbose_name_plural': 'Прочитанные книги',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
