# Generated by Django 4.2.7 on 2025-04-04 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=244, null=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(max_length=244, null=True, verbose_name='заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='', verbose_name='фото')),
                ('links', models.URLField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'страница читателям',
                'verbose_name_plural': 'страницы читателям',
            },
        ),
        migrations.CreateModel(
            name='Graphic_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=244, null=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(max_length=244, null=True, verbose_name='заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'страница читателям про график',
                'verbose_name_plural': 'страницы читателям про график',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=244, verbose_name='график работы')),
                ('work_ru', models.CharField(max_length=244, null=True, verbose_name='график работы')),
                ('work_ky', models.CharField(max_length=244, null=True, verbose_name='график работы')),
                ('citizens', models.CharField(max_length=244, verbose_name='график приема граждан')),
                ('citizens_ru', models.CharField(max_length=244, null=True, verbose_name='график приема граждан')),
                ('citizens_ky', models.CharField(max_length=244, null=True, verbose_name='график приема граждан')),
                ('hall', models.CharField(max_length=244, verbose_name='зал читателей')),
                ('hall_ru', models.CharField(max_length=244, null=True, verbose_name='зал читателей')),
                ('hall_ky', models.CharField(max_length=244, null=True, verbose_name='зал читателей')),
                ('readers', models.CharField(max_length=244, verbose_name='рейтинг читателей')),
                ('readers_ru', models.CharField(max_length=244, null=True, verbose_name='рейтинг читателей')),
                ('readers_ky', models.CharField(max_length=244, null=True, verbose_name='рейтинг читателей')),
                ('books', models.CharField(max_length=244, verbose_name='рейтинг книг')),
                ('books_ru', models.CharField(max_length=244, null=True, verbose_name='рейтинг книг')),
                ('books_ky', models.CharField(max_length=244, null=True, verbose_name='рейтинг книг')),
            ],
            options={
                'verbose_name': 'основные настройки страницы читателя',
                'verbose_name_plural': 'основные настройки страницы читателей',
            },
        ),
    ]
