# Generated by Django 4.2.7 on 2025-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_for_readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=244, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=244, null=True, verbose_name='Название')),
                ('hosts', models.CharField(max_length=244, verbose_name='Принимающие')),
                ('hosts_ru', models.CharField(max_length=244, null=True, verbose_name='Принимающие')),
                ('hosts_ky', models.CharField(max_length=244, null=True, verbose_name='Принимающие')),
                ('schedule', models.CharField(max_length=244, verbose_name='График приемов')),
                ('schedule_ru', models.CharField(max_length=244, null=True, verbose_name='График приемов')),
                ('schedule_ky', models.CharField(max_length=244, null=True, verbose_name='График приемов')),
            ],
        ),
        migrations.CreateModel(
            name='ReadBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, verbose_name='читательные залы')),
                ('title_ru', models.CharField(max_length=244, null=True, verbose_name='читательные залы')),
                ('title_ky', models.CharField(max_length=244, null=True, verbose_name='читательные залы')),
                ('link', models.URLField(blank=True, max_length=244, null=True, verbose_name='ссылка')),
            ],
        ),
        migrations.AlterField(
            model_name='titles',
            name='citizens',
            field=models.CharField(max_length=244, verbose_name='график приема граждан директора'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='citizens_ky',
            field=models.CharField(max_length=244, null=True, verbose_name='график приема граждан директора'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='citizens_ru',
            field=models.CharField(max_length=244, null=True, verbose_name='график приема граждан директора'),
        ),
    ]
