# Generated by Django 4.2.7 on 2025-05-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_for_readers', '0002_appointment_readbase_alter_titles_citizens_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'График приема', 'verbose_name_plural': 'График приемов'},
        ),
        migrations.AlterModelOptions(
            name='readbase',
            options={'verbose_name': 'Читательный Зал', 'verbose_name_plural': 'Читательные Залы'},
        ),
    ]
