# Generated by Django 4.2.7 on 2025-04-04 10:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, verbose_name='Первый заголовок')),
                ('title_1_ru', models.CharField(max_length=255, null=True, verbose_name='Первый заголовок')),
                ('title_1_ky', models.CharField(max_length=255, null=True, verbose_name='Первый заголовок')),
                ('title_2', models.CharField(max_length=255, verbose_name='Второй заголовок')),
                ('title_2_ru', models.CharField(max_length=255, null=True, verbose_name='Второй заголовок')),
                ('title_2_ky', models.CharField(max_length=255, null=True, verbose_name='Второй заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image_1', models.ImageField(upload_to='First-image/', verbose_name='Первое изображение')),
                ('image_2', models.ImageField(upload_to='Second-image/', verbose_name='Второе изображение')),
                ('image_3', models.ImageField(upload_to='Third-image/', verbose_name='Третье изображение')),
            ],
            options={
                'verbose_name': 'О библиотеке',
                'verbose_name_plural': 'О библиотеке',
            },
        ),
        migrations.CreateModel(
            name='Acts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='acts-image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Акт, Регулирующие деятельность',
                'verbose_name_plural': 'Акты, Регулирующие деятельности',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history-image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Должность')),
                ('role_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('role_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='management-image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
            },
        ),
        migrations.CreateModel(
            name='StructureAndLibraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='StructureAndLibraries-image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Структура и библиотеки',
                'verbose_name_plural': 'Структуры и библиотеки',
            },
        ),
        migrations.CreateModel(
            name='TitlesLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, verbose_name='Заголовок Руководство')),
                ('title_1_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок Руководство')),
                ('title_1_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок Руководство')),
                ('title_2', models.CharField(max_length=255, verbose_name='Заголовок Структура и Библиотеки')),
                ('title_2_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок Структура и Библиотеки')),
                ('title_2_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок Структура и Библиотеки')),
                ('title_3', models.CharField(max_length=255, verbose_name='Заголовок Акты Регулирующие деятельность')),
                ('title_3_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок Акты Регулирующие деятельность')),
                ('title_3_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок Акты Регулирующие деятельность')),
                ('title_4', models.CharField(max_length=255, verbose_name='Заголовок История')),
                ('title_4_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок История')),
                ('title_4_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок История')),
            ],
            options={
                'verbose_name': 'Заголовок библиотеки',
                'verbose_name_plural': 'Заголовки библиотек',
            },
        ),
    ]
