# Generated by Django 4.2.7 on 2025-04-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acts',
            name='image',
        ),
        migrations.AddField(
            model_name='acts',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Сыллка в актах'),
        ),
    ]
