# Generated by Django 4.2.7 on 2025-04-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории услуг (например, Основные услуги, Культурные услуги).', max_length=255, verbose_name='Название категории')),
                ('name_ru', models.CharField(help_text='Введите название категории услуг (например, Основные услуги, Культурные услуги).', max_length=255, null=True, verbose_name='Название категории')),
                ('name_ky', models.CharField(help_text='Введите название категории услуг (например, Основные услуги, Культурные услуги).', max_length=255, null=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='ServiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='НАШИ УСЛУГИ – БОЛЬШЕ, ЧЕМ ПРОСТО КНИГИ', help_text='Введите главный заголовок страницы услуг.', max_length=255, verbose_name='Главный заголовок')),
                ('title_ru', models.CharField(default='НАШИ УСЛУГИ – БОЛЬШЕ, ЧЕМ ПРОСТО КНИГИ', help_text='Введите главный заголовок страницы услуг.', max_length=255, null=True, verbose_name='Главный заголовок')),
                ('title_ky', models.CharField(default='НАШИ УСЛУГИ – БОЛЬШЕ, ЧЕМ ПРОСТО КНИГИ', help_text='Введите главный заголовок страницы услуг.', max_length=255, null=True, verbose_name='Главный заголовок')),
                ('description', models.TextField(blank=True, help_text='Введите описание, которое будет отображаться под заголовком.', null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, help_text='Введите описание, которое будет отображаться под заголовком.', null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, help_text='Введите описание, которое будет отображаться под заголовком.', null=True, verbose_name='Описание')),
                ('image1', models.ImageField(blank=True, help_text='Загрузите первое изображение (слева).', null=True, upload_to='header/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, help_text='Загрузите второе изображение (в центре).', null=True, upload_to='header/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, help_text='Загрузите третье изображение (справа).', null=True, upload_to='header/', verbose_name='Изображение 3')),
            ],
            options={
                'verbose_name': 'Заголовок страницы',
                'verbose_name_plural': 'Заголовки страниц',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название услуги.', max_length=255, verbose_name='Название услуги')),
                ('title_ru', models.CharField(help_text='Введите название услуги.', max_length=255, null=True, verbose_name='Название услуги')),
                ('title_ky', models.CharField(help_text='Введите название услуги.', max_length=255, null=True, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, help_text='Введите описание услуги (необязательно).', null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, help_text='Введите описание услуги (необязательно).', null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, help_text='Введите описание услуги (необязательно).', null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение, иллюстрирующее услугу (необязательно).', null=True, upload_to='services/', verbose_name='Изображение')),
                ('category', models.ForeignKey(help_text='Выберите категорию, к которой относится эта услуга.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Категория')),
                ('category_ky', models.ForeignKey(help_text='Выберите категорию, к которой относится эта услуга.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Категория')),
                ('category_ru', models.ForeignKey(help_text='Выберите категорию, к которой относится эта услуга.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
