# Generated by Django 4.2.7 on 2025-04-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceheader',
            options={'verbose_name': '', 'verbose_name_plural': 'Хедер страницы услуги'},
        ),
    ]
