# Generated by Django 4.2.7 on 2025-05-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceheader_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceheader',
            options={'verbose_name': 'Заголовок страницы', 'verbose_name_plural': 'Заголовки страниц'},
        ),
    ]
