# Generated by Django 4.2.7 on 2025-04-04 09:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='library-support/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Поддержка библиотеки',
                'verbose_name_plural': 'Поддержка библиотеки',
            },
        ),
        migrations.CreateModel(
            name='LibraryTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, verbose_name='Ценности библиотеки')),
                ('title_1_ru', models.CharField(max_length=255, null=True, verbose_name='Ценности библиотеки')),
                ('title_1_ky', models.CharField(max_length=255, null=True, verbose_name='Ценности библиотеки')),
                ('title_2', models.CharField(max_length=255, verbose_name='Наши партнеры')),
                ('title_2_ru', models.CharField(max_length=255, null=True, verbose_name='Наши партнеры')),
                ('title_2_ky', models.CharField(max_length=255, null=True, verbose_name='Наши партнеры')),
                ('title_3', models.CharField(max_length=255, verbose_name='Способ оплаты')),
                ('title_3_ru', models.CharField(max_length=255, null=True, verbose_name='Способ оплаты')),
                ('title_3_ky', models.CharField(max_length=255, null=True, verbose_name='Способ оплаты')),
                ('left_description', ckeditor.fields.RichTextField(verbose_name='Оплата наличными')),
                ('left_description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Оплата наличными')),
                ('left_description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Оплата наличными')),
                ('right_description', ckeditor.fields.RichTextField(verbose_name='Оплата перевод')),
                ('right_description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Оплата перевод')),
                ('right_description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Оплата перевод')),
            ],
            options={
                'verbose_name': 'Заголовки',
                'verbose_name_plural': 'Заголовки',
            },
        ),
        migrations.CreateModel(
            name='LibraryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок ценности')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок ценности')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок ценности')),
                ('icon', models.ImageField(upload_to='library-values/icons/', verbose_name='Иконка')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('short_description_ru', models.TextField(null=True, verbose_name='Краткое описание')),
                ('short_description_ky', models.TextField(null=True, verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='Полное описание')),
                ('full_description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание')),
                ('full_description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Ценность библиотеки',
                'verbose_name_plural': 'Ценности библиотеки',
            },
        ),
    ]
