# Generated by Django 4.2.7 on 2025-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('image_logo', models.ImageField(upload_to='pay/', verbose_name='Логотип')),
                ('image_qr', models.ImageField(upload_to='qr/', verbose_name='Qr')),
                ('links', models.URLField(verbose_name='Ссылка')),
            ],
        ),
    ]
